In [58]:
import numpy as np
from sklearn import preprocessing

## Convolution

In [59]:
def normalize(arr,precision = 2 ,*minimization):
    scalar = preprocessing.MinMaxScaler()
    result = np.round(scalar.fit_transform(arr), precision)
    for maxColumn in minimization:
        result[:, maxColumn - 1] = 1 - result[:, maxColumn - 1]
    return result

In [60]:
inputs = np.array([
    [50, 70, 50, 90], #t1
    [60, 60, 80, 70], #t2
    [70, 90, 60, 60], #t3
    [80, 100, 90, 100] #t4
])
Cs = np.array([0.15,0.3, 0.15, 0.4 ])

## Additive Convolution

In [61]:
def convolution_additive(inputs, ws, *minimization):
    print('############ Additive Convolution ############\n')
    print(inputs)
    print('\n############ Normalized Inputs ############\n')
    normalized_inputs = normalize(inputs, *minimization)
    print(normalized_inputs)
    print('\n############ Sum of weights multiply by rows ############\n')
    ws_mult_by_rows = normalized_inputs @ Cs
    print(ws_mult_by_rows)
    print('\n############ Result ############\n')
    result = np.argmax(ws_mult_by_rows)
    print(f'Our best alternative is {result + 1} which is {inputs[result]}')
    

In [68]:
convolution_additive(inputs, Cs, 2)

############ Additive Convolution ############

[[ 50  70  50  90]
 [ 60  60  80  70]
 [ 70  90  60  60]
 [ 80 100  90 100]]

############ Normalized Inputs ############

[[0.   0.25 0.   0.75]
 [0.33 0.   0.75 0.25]
 [0.67 0.75 0.25 0.  ]
 [1.   1.   1.   1.  ]]

############ Sum of weights multiply by rows ############

[0.375 0.262 0.363 1.   ]

############ Result ############

Our best alternative is 4 which is [ 80 100  90 100]


## Multiplitive Convolution

In [56]:
def convolution_multiplitive(inputs, ws, *minimization):
    print('############ Additive Convolution ############\n')
    print(inputs)
    print('\n############ Normalized Inputs ############\n')
    normalized_inputs = normalize(inputs, *minimization)
    print(normalized_inputs)
    print('\n############ Product of T to the power of W ############\n')
    ts_to_the_power_ws = np.power(normalized_inputs, Cs)
    ts_product = np.product(ts_to_the_power_ws, axis=1)
    print(ts_product)
    print('\n############ Result ############\n')
    result = np.argmax(ws_mult_by_rows)
    print(f'Our best alternative is {result + 1} which is {inputs[result]}')

In [57]:
convolution_multiplitive(inputs, Cs, 2)

############ Additive Convolution ############

[[ 50  70  50  90]
 [ 60  60  80  70]
 [ 70  90  60  60]
 [ 80 100  90 100]]

############ Normalized Inputs ############

[[0.   0.25 0.   0.75]
 [0.33 0.   0.75 0.25]
 [0.67 0.75 0.25 0.  ]
 [1.   1.   1.   1.  ]]

############ Product of T to the power of W ############

[0. 0. 0. 1.]

############ Result ############

Our best alternative is 4 which is [ 80 100  90 100]
